import sys
import os
from pathlib import Path

TEMPLATE = '''"""
{class_name} Strategy
Generated by scripts/create_strategy.py
"""

from src.policy.scanners import Scanner, ScanResult
from src.features.state import MarketState
from src.features.pipeline import FeatureBundle
from typing import Dict, Any

class {class_name}(Scanner):
    """
    TODO: Add description of your strategy here.
    """

    @property
    def scanner_id(self) -> str:
        return "{scanner_id}"

    def scan(self, state: MarketState, features: FeatureBundle) -> ScanResult:
        """
        Check for entry conditions on every bar.
        
        Available data:
        - state.timestamp, state.current_price
        - features.indicators:
            - ema_5m_20, ema_5m_200, rsi_5m_14, atr_5m_14, vwap_session
        - features.levels:
            - pdc (Previous Day Close), pdh, pdl
        """
        
        # 1. Define Logic Here
        triggered = False
        context: Dict[str, Any] = {{}}
        
        # Example:
        # rsi = features.indicators.rsi_5m_14
        # if rsi < 30:
        #     triggered = True
        #     context = {{
        #         "direction": "LONG",
        #         "reason": f"RSI oversold: {{rsi:.2f}}",
        #         "entry_price": state.current_price
        #     }}

        return ScanResult(
            scanner_id=self.scanner_id,
            triggered=triggered,
            context=context,
            score=1.0 if triggered else 0.0
        )
'''

def to_camel_case(snake_str):
    return "".join(x.capitalize() for x in snake_str.lower().split("_"))

def create_strategy(name):
    base_dir = Path("src/policy/library")
    base_dir.mkdir(parents=True, exist_ok=True)
    
    filename = name.lower().replace("-", "_")
    if not filename.endswith(".py"):
        filename += ".py"
        
    filepath = base_dir / filename
    
    if filepath.exists():
        print(f"❌ Error: Strategy file already exists: {filepath}")
        sys.exit(1)
        
    scanner_id = filename.replace(".py", "")
    class_name = to_camel_case(scanner_id) + "Scanner"
    
    content = TEMPLATE.format(
        class_name=class_name,
        scanner_id=scanner_id
    )
    
    with open(filepath, "w") as f:
        f.write(content)
        
    print(f"✅ Strategy scaffolded: {filepath}")
    print(f"   Class: {class_name}")
    print(f"   ID:    {scanner_id}")
    print(f"\nNext steps:")
    print(f"1. Edit {filepath} to implement your logic.")
    print(f"2. Run backtest: python scripts/backtest_walkforward_viz.py --scanner {scanner_id} --start-date ...")
    print(f"3. Validate:     python golden/validate_run.py results/viz/...")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/create_strategy.py <strategy_name>")
        print("Example: python scripts/create_strategy.py my_cool_strategy")
        sys.exit(1)
        
    create_strategy(sys.argv[1])
